server:
  port: 8889

spring:
  application:
    name: eureka-client #服务名

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/ #注册中心地址
      #eureka.client.serviceUrl.defaultZone = http://127.0.0.1:1111/eureka/,http://127.0.0.1:11112/eureka/